---
title: "R19 budbreak"
author: "Patrick Snelgar"
date: "14/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

require(tidyverse)
require(magrittr)
require(lubridate)
library(scales)

```


```{r functions}
getValidColumns <- function(data){
	names <- colnames(data)
	asDates <- dmy(paste(names, "2019"))
	return(which(!is.na(asDates)))
}

mergeLogAndTranspose <- function(data, log, IDcolumn = 1){
	longFormat <- data %>%
		gather(key = "Date", value = "OpenBuds", -IDcolumn) %>%
		group_by_at(colnames(data)[IDcolumn]) %>%
		mutate(BudbreakPercentage = OpenBuds / max(OpenBuds)) %>%
		arrange_at(colnames(data)[1])
	
	longFormat$information <- sapply(1:nrow(longFormat), function(x) log$information[log$CaneID == longFormat$CaneID[x] & log$Date == longFormat$Date[x]][1])
	
	longFormat %<>% mutate(Date = dmy(paste(Date, "2019")))
	
	return(longFormat)
}

fillDataFrame <- function(data, IDcolumn = 1){
	processed <- select(data,
						c(IDcolumn, getValidColumns(data)))
	
	log <-  data.frame(CaneID = double(), Date = character(), information = character(), stringsAsFactors = FALSE)
	
	for(i in seq_along(processed[[1]])){
		maxValue <- 0
		
		for(j in seq_along(processed)[-1]){
			if(any(c("x", "X", "xx", NA) %in% processed[[i,j]]))
				processed[[i,j]] <- maxValue
			
			if(processed[[i,j]] > maxValue)
				maxValue <- processed[[i,j]]
			
			if(processed[[i,j]] < maxValue){
				log %<>% bind_rows(., data.frame(CaneID = processed[i,1], 
												 Date = names(processed)[j],
												 information = paste("Value smaller than max: previous =", processed[[i,j]], " new =", maxValue),
												 stringsAsFactors = FALSE))
				processed[[i,j]] <-  maxValue
			}
		}
	}
	
	return(mergeLogAndTranspose(processed, log))
}
```

```{r data_import}

treatmentsR19 <- read_csv("./data/treatmentsR19.csv")%>%
					rename(CaneID = 1, Treatment = 2)


rawBB_R19 <- read_csv("./data/R19_budbreak.csv", na = c("x", NA)) %>%
	rename(CaneID = 1)

processedR19_budbreak <- fillDataFrame(rawBB_R19)

processedR19_budbreak$Treatment <- sapply(seq_along(processedR19_budbreak$CaneID), 
										  function(x) treatmentsR19$Treatment[processedR19_budbreak$CaneID[x] == treatmentsR19$CaneID])

```

```{r vis}

# looking at just the early & late HC aplications vs control
# as supporting evidence for the flowers per shoot distribution.
processedR19_budbreak %>%
	mutate(treatment = gsub("[ ][ ]+", " ", Treatment), timing = str_extract(treatment, "[LMEV]+$"),
				   chemical = gsub("^([A-Za-z ]+[ ][0-9]%)(.+)", "\\1", treatment)) %>%
	filter(treatment %in% c("Untreated control", "3% HiCane + 0.2% Driftstop E", "3% HiCane L")) %>%
	group_by(treatment, Date) %>%
	summarise(mean_bb_perc = mean(BudbreakPercentage)) %>%
	ggplot() +
		geom_line(aes(Date, mean_bb_perc, colour = treatment)) + 
		scale_x_date(breaks = pretty_breaks(12)) + 
		labs(colour = "Chemical x Timing", y = "Budbreak percentage")


ggsave("./Graphs/R19 - budbreak curves (HC & Control).png", width = 10, height = 6)

```